# Generated by Django 5.2.4 on 2025-07-20 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('blank', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('study_hours', models.FloatField(default=0)),
                ('practice', models.IntegerField(default=0)),
                ('risk_management', models.FloatField(default=0)),
                ('answering_efficiency', models.FloatField(default=0)),
                ('study_productivity', models.FloatField(default=0)),
                ('practice_effectiveness', models.FloatField(default=0)),
                ('time_utilization', models.FloatField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='analyzer.exam')),
            ],
        ),
    ]
